# Generated by Django 2.2.3 on 2020-03-30 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cas',
            options={'verbose_name': 'cas', 'verbose_name_plural': 'cas'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'membre'},
        ),
        migrations.AlterModelOptions(
            name='naturebesoin',
            options={'ordering': ('classification', 'libelle'), 'verbose_name': 'nature de demande'},
        ),
        migrations.AlterModelOptions(
            name='provuser',
            options={'ordering': ('username',), 'verbose_name': 'utilisateur'},
        ),
        migrations.AddField(
            model_name='naturebesoin',
            name='classification',
            field=models.CharField(choices=[('S', 'Social'), ('M', 'Mission')], default='S', max_length=1, verbose_name='classification du cas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provuser',
            name='telephone1',
            field=models.CharField(default='', max_length=32, verbose_name='téléphone 1'),
        ),
        migrations.AlterField(
            model_name='provuser',
            name='telephone2',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='téléphone 2'),
        ),
        migrations.CreateModel(
            name='AffectationNonLibere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.PositiveIntegerField(verbose_name='montant à récupérer')),
                ('collecteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collecteurs', to=settings.AUTH_USER_MODEL, verbose_name='collecteur')),
                ('cotisant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cotisants', to=settings.AUTH_USER_MODEL, verbose_name='cotisant')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Cotisation', verbose_name='cotisation')),
            ],
            options={
                'verbose_name': 'affectation cotisation non libérée',
            },
        ),
    ]
