# Generated by Django 2.2.3 on 2020-04-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200330_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='anciennete_foi',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ancienneté dans la foi'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nb_enfants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='cas',
            name='anciennete_foi',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ancienneté dans la foi'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='classification',
            field=models.CharField(choices=[('S', 'Social'), ('M', 'Mission')], default='S', max_length=1, verbose_name='classification du cas'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='compte_rendu',
            field=models.TextField(blank=True, null=True, verbose_name='compte-rendu du cas'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='exposé du cas'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='montant_alloue',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='montant alloué'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='montant_sollicite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='montant solllicité'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='nature',
            field=models.ManyToManyField(blank=True, null=True, to='blog.NatureBesoin', verbose_name='nature(s) du cas'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='nb_enfants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='cas',
            name='sollicitation_externe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='solllicitation hors Providence'),
        ),
        migrations.AlterField(
            model_name='naturebesoin',
            name='classification',
            field=models.CharField(choices=[('S', 'Social'), ('M', 'Mission')], max_length=1, verbose_name='classification'),
        ),
    ]
