# Generated by Django 2.2.3 on 2020-04-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cas',
            name='nature',
            field=models.ManyToManyField(to='blog.NatureBesoin', verbose_name='nature(s) du cas'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='nom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
