# Generated by Django 2.2.3 on 2020-04-05 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200405_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reunion',
            options={'ordering': ('-date_reunion',), 'verbose_name': 'réunion'},
        ),
        migrations.AddField(
            model_name='provuser',
            name='personne_physique',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cas',
            name='nature',
            field=models.ManyToManyField(blank=True, to='blog.NatureBesoin', verbose_name='nature(s) du cas'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='compte_rendu',
            field=models.TextField(blank=True, null=True, verbose_name='compte-rendu de la réunion'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='lieu_reunion',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='lieu de la réunion'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='liste_presence',
            field=models.ManyToManyField(blank=True, related_name='presences', to=settings.AUTH_USER_MODEL, verbose_name='membres présents'),
        ),
    ]
