# Generated by Django 2.2.3 on 2020-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200405_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas',
            name='suivi',
            field=models.CharField(blank=True, choices=[('O', 'Ouvert'), ('C', 'Clos'), ('R', 'Reconduit'), ('P', 'Reporté'), ('A', 'Annulé')], default='O', max_length=1, null=True, verbose_name='suivi du cas'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='mission_libere',
            field=models.BooleanField(default=False, verbose_name='montant mission libéré ?'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='social_libere',
            field=models.BooleanField(default=False, verbose_name='montant social libéré ?'),
        ),
    ]
