# Generated by Django 2.2.3 on 2020-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200409_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='montant_mission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant_social',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
