# Generated by Django 2.2.3 on 2020-04-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200409_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'verbose_name': 'cotisation du mois', 'verbose_name_plural': 'cotisations du mois'},
        ),
        migrations.RemoveField(
            model_name='affectationnonlibere',
            name='cotisant',
        ),
        migrations.AddField(
            model_name='affectationnonlibere',
            name='reunion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='blog.Reunion', verbose_name='réunion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectationnonlibere',
            name='cotisation',
            field=models.ForeignKey(limit_choices_to=models.Q(('social_libere', False), ('mission_libere', False), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='blog.Cotisation', verbose_name='cotisation'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_beneficiaire', to='blog.Beneficiaire', verbose_name='bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='cas',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_reunion', to='blog.Reunion', verbose_name='réunion'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='blog.Reunion', verbose_name='réunion'),
        ),
    ]
