# Generated by Django 2.2.3 on 2020-04-13 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200413_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationnonlibere',
            options={'verbose_name': 'affectation de cotisation non libérée', 'verbose_name_plural': 'affectations des cotisations non libérées'},
        ),
        migrations.AddField(
            model_name='affectationnonlibere',
            name='classification',
            field=models.CharField(choices=[('S', 'Social'), ('M', 'Mission')], default='S', max_length=1, verbose_name='classification du cas'),
        ),
        migrations.AlterField(
            model_name='affectationnonlibere',
            name='collecteur',
            field=models.ForeignKey(limit_choices_to={'personne_physique': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collecteurs', to=settings.AUTH_USER_MODEL, verbose_name='collecteur'),
        ),
    ]
