# Generated by Django 2.2.3 on 2020-04-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200413_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectationnonlibere',
            name='classification',
        ),
        migrations.AddField(
            model_name='affectationnonlibere',
            name='cas',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='affectation_cas', to='blog.Cas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectationnonlibere',
            name='collecteur',
            field=models.ForeignKey(limit_choices_to={'personne_physique': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collecteurs', to=settings.AUTH_USER_MODEL, verbose_name='Collecté par'),
        ),
        migrations.AlterField(
            model_name='affectationnonlibere',
            name='cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cotisation', verbose_name='cotisation de'),
        ),
    ]
