# Generated by Django 2.2.3 on 2020-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200413_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCotisationNonLiberee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='identifiant')),
                ('montant_social', models.PositiveIntegerField()),
                ('social_libere', models.BooleanField(verbose_name='montant social libéré ?')),
                ('montant_mission', models.PositiveIntegerField()),
                ('mission_libere', models.BooleanField(verbose_name='montant mission libéré ?')),
            ],
            options={
                'verbose_name': 'cotisation du mois non libérée',
                'verbose_name_plural': 'cotisations du mois non libérées',
                'db_table': 'v_cotisation_non_liberee',
                'managed': False,
            },
        ),
    ]
