# Generated by Django 2.2.3 on 2020-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_vcotisationnonliberee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueCotisationNonLiberee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='identifiant')),
                ('montant_social', models.PositiveIntegerField(blank=True, null=True)),
                ('social_libere', models.BooleanField(blank=True, null=True, verbose_name='montant social libéré ?')),
                ('montant_mission', models.PositiveIntegerField(blank=True, null=True)),
                ('mission_libere', models.BooleanField(blank=True, null=True, verbose_name='montant mission libéré ?')),
                ('reste_cotis_social', models.IntegerField(blank=True, null=True, verbose_name='reste social')),
                ('reste_cotis_mission', models.IntegerField(blank=True, null=True, verbose_name='reste mission')),
            ],
            options={
                'verbose_name': 'cotisation du mois non libérée',
                'verbose_name_plural': 'cotisations du mois non libérées',
                'db_table': 'v_cotisation_non_liberee',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VCotisationNonLiberee',
        ),
        migrations.AlterModelOptions(
            name='communaute',
            options={'ordering': ('nom',), 'verbose_name': 'communauté chrétienne', 'verbose_name_plural': 'communautés chrétiennes'},
        ),
        migrations.AlterModelOptions(
            name='famillecommunaute',
            options={'ordering': ('nom',), 'verbose_name': 'groupe de communauté', 'verbose_name_plural': 'groupes de communautés'},
        ),
        migrations.AlterModelOptions(
            name='naturebesoin',
            options={'ordering': ('classification', 'libelle'), 'verbose_name': 'nature de besoin', 'verbose_name_plural': 'natures de besoins'},
        ),
        migrations.AddField(
            model_name='provuser',
            name='peut_cotiser',
            field=models.BooleanField(default=True),
        ),
    ]
